services:
  db:
    image: postgres:16
    container_name: odoo-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  odoo:
    image: odoo:${ODOO_VERSION}
    container_name: odoo-app
    depends_on:
      - db
    ports:
      - "${ODOO_HTTP_PORT}:8069"
    environment:
      HOST: db
      PORT: 5432
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - odoo_data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./addons:/mnt/extra-addons
    command: ["odoo", "--config=/etc/odoo/odoo.conf", "--dev=all"]

volumes:
  pgdata:
  odoo_data: